### ISSUE TITLE
1.26 nodes fail to join the cluster with custom VPC domain-name

### ISSUE THREAD

**Issue by watkinsmike** [awslabs/amazon-eks-ami#1263]
**What happened**:
1.26 AMI Nodes fail to join 1.26 clusters. In both scenarios of upgrading from 1.25 to 1.26 and new clusters starting fresh with 1.26

**What you expected to happen**:
The nodes to join the cluster

**Anything else we need to know?**:
* Using manged node groups.
* The exact same Terraform deployment configuration works on 1.25. The only thing changed is the version for cluster/ami which triggers the failure on both upgrades and new clusters.
* VPC DHCP domain name is in the format: `ec2.internal acmedev.com`

**Environment**:
- AWS Region: `us-east-1`
- Instance Type(s): `m6a`
- EKS Platform version: `"eks.1"`
- Kubernetes version: `"1.26"`
- AMI Version: `amazon-eks-node-1.26-v20230406`
- Kernel (e.g. `uname -a`): `Linux ip-10-100-13-0.ec2.internalacmedev.com 5.10.173-154.642.amzn2.x86_64 #1 SMP Wed Mar 15 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node): 

```
BASE_AMI_ID="ami-099e00fe4091e48af"
BUILD_TIME="Thu Apr  6 01:36:39 UTC 2023"
BUILD_KERNEL="5.10.173-154.642.amzn2.x86_64"
ARCH="x86_64"
```
I believe the change in `cloud-provider` from `aws` to `external` has created an issue where our hostname for the kubelet is different between 1.25 and 1.26. This causes the aws iam authenticator node bootstrap logic to fail to register with the cluster because the hostname in the requests are not the same.

hostnamed logs are the exact same on 1.25 and 1.26 nodes, including the "warning"
```
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed pretty host name to 'ip-10-100-13-0.ec2.internal acmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed static host name to 'ip-10-100-13-0.ec2.internalacmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 systemd-hostnamed: Changed host name to 'ip-10-100-13-0.ec2.internalacmedev.com'
Apr 13 13:55:48 ip-10-100-13-0 cloud-init: Apr 13 13:55:48 cloud-init[2209]: util.py[WARNING]: Failed to non-persistently adjust the system hostname to ip-10-100-13-0.ec2.internal acmedev.com
```

We are not changing any of the kubelet arguments from their AMI defaults. The only thing we are doing is adding some labels/taints to the nodes via the managed node group terraform resources. No hostname overrides.
```
Apr 13 13:55:53 ip-10-100-13-0 kubelet: I0413 13:55:53.946396    2944 flags.go:64] FLAG: --cloud-provider="external"
Apr 13 13:55:53 ip-10-100-13-0 kubelet: I0413 13:55:53.946638    2944 flags.go:64] FLAG: --hostname-override=""
```

Pertinent messages that indicate node join failures.
```Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.191968    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasSufficientMemory"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.192348    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasNoDiskPressure"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.192745    2944 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-100-13-0.ec2.internalacmedev.com" event="NodeHasSufficientPID"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.193204    2944 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.765164    2944 controller.go:146] failed to ensure lease exists, will retry in 200ms, error: leases.coordination.k8s.io "ip-10-100-13-0.ec2.internalacmedev.com" is forbidden: User "system:node:ip-10-100-13-0.ec2.internal" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.765885    2944 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "ip-10-100-13-0.ec2.internalacmedev.com" is forbidden: User "system:node:ip-10-100-13-0.ec2.internal" cannot get resource "csinodes" in API group "storage.k8s.io" at the cluster scope: can only access CSINode with the same name as the requesting node
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.766850    2944 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-10-100-13-0.ec2.internalacmedev.com\" is forbidden: node \"ip-10-100-13-0.ec2.internal\" is not allowed to modify node \"ip-10-100-13-0.ec2.internalacmedev.com\"" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: I0413 13:55:54.969984    2944 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-100-13-0.ec2.internalacmedev.com"
Apr 13 13:55:54 ip-10-100-13-0 kubelet: E0413 13:55:54.972246    2944 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes \"ip-10-100-13-0.ec2.internalacmedev.com\" is forbidden: node \"ip-10-100-13-0.ec2.internal\" is not allowed to modify node \"ip-10-100-13-0.ec2.internalacmedev.com\"" node="ip-10-100-13-0.ec2.internalacmedev.com"
```

On the 1.25 nodes using `cloud-provider=aws` we can see the logs like:
```
Apr 12 15:14:31 ip-10-100-12-210 kubelet: I0412 15:14:31.176819    2906 server.go:993] "Cloud provider determined current node" nodeName="ip-10-100-12-210.ec2.internal"
```
https://github.com/kubernetes/kubernetes/blob/v1.26.2/cmd/kubelet/app/server.go#L989 which does not contain the `acmedev.com` appended to it.

The nodename returned in 1.25 aligns with with the templated private DNS name returned from the https://github.com/kubernetes-sigs/aws-iam-authenticator/tree/master that allows bootstrapping nodes. Since we are not using the aws cloud provider in 1.26 we might be getting back a different value for nodename which does not align.

Since the change to the `cloud-provider=external` I beieve we are returning the hostname that we would get from `hostname` or `uname -n`  e.g. `ip-10-100-13-0.ec2.internalacmedev.com` which does not align with what is returned from the EC2 api when getting the private DNS name for auth. Our node config in the aws-auth cm is standard:
```
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::1234567890:role/role-name"
      "username": "system:node:{{EC2PrivateDNSName}}"
```

**Comment by cartermckinnon** [comment]
@watkinsmike are you using managed nodegroups?

**Comment by watkinsmike** [comment]
> @watkinsmike are you using managed nodegroups?

yes

**Comment by cartermckinnon** [comment]
Is it intentional that the DHCP `domain-name` is `ec2.internal acmedev.com` (with a space character between `ec2.internal` and `acmedev.com`?

Something does seem awry in the authenticator, anyway. I'm looking into it. If you'd like to email me your nodegroup ARN, that would help: mckdev@amazon.com

**Comment by watkinsmike** [comment]
> Is it intentional that the DHCP `domain-name` is `ec2.internal acmedev.com` (with a space character between `ec2.internal` and `acmedev.com`)?

It was intentional when it was created many years ago, but I can only guess at the reason right now. It does seem like the space separated domain name is supported by AWS for creating `/etc/resolv.conf` but not entirely sure about the usage of the internal domain and the published domain pattern.

> Something does seem awry in the authenticator, regardless. I'm looking into it. If you'd like to email me your nodegroup ARN, that would help: [mckdev@amazon.com](mailto:mckdev@amazon.com)

Done!

**Comment by cartermckinnon** [comment]
I'm able to reproduce the issue, and have a hunch about the cause. At this point, I don't have a workaround. I'll update here as I learn more. 👍

**Comment by cartermckinnon** [comment]
My current understanding is:

When you use a custom `domain-name` in the DHCP option set of your VPC, `cloud-init` will set `/etc/hostname` on the instance to `$HOSTNAME.$DOMAIN`, where `HOSTNAME` is either an IP-based (`ip-x-x-x-x`) or resource-based (`i-abcdefg123`) name, and `DOMAIN` is your `domain-name`.

Kubelet will try to create a Node object using that value; but, the `aws-iam-authenticator` server running in the control plane will associate the incoming request with the username `system:node:$PRIVATE_DNS_NAME`, where `PRIVATE_DNS_NAME` is the instance's `PrivateDnsName` (from the EC2 DescribeInstances API). So, the request will be rejected as unauthorized, and the node will never join the cluster.

**Comment by cartermckinnon** [comment]
In my repro, nodes will join the cluster if you set your VPC's `enableDnsHostname` to `false`. This results in the EC2 API returning your custom domain in the instance's `PrivateDnsName`, and things work as expected.

I believe this wasn't necessary in 1.25, because kubelet's in-tree cloud provider would use the `PrivateDnsName` from EC2 to determine the hostname, not `/etc/hostname`, etc.

**Comment by cartermckinnon** [comment]
@watkinsmike I've got a fix up in #1264 . I'll do some final validation tomorrow before I get it rolling. Sorry for the hassle!

If you run custom AMI nodegroups, you can mitigate this in your user data by adding `--hostname-override` to `--kubelet-extra-args` like I've done in the PR description.

**Comment by AndreiBanaruTakeda** [comment]
We are also impacted by this.

Any thoughts on the potential conflict with the CIS Benchmark for EKS v1.2.0 - [3.2.8 Ensure that the --hostname-override argument is not set](https://workbench.cisecurity.org/sections/1282199/recommendations/2070838)

**Comment by cartermckinnon** [comment]
@AndreiBanaruTakeda the CIS recommendation isn't unreasonable, but I wouldn't consider this a critical tenant. The text previously read:
> 	Some cloud providers may require this flag to ensure that hostname matches names issued by the cloud provider. In these environments, this recommendation should not apply. 

That being said, I'm looking into ways to address this elsewhere -- it's not ideal for every node to address this individually with `--hostname-override`.

**Comment by pnpn** [comment]
Hi ! 
I'm piggy-backing on this issue just to tell you that we faces this issue today despite the fact that we do not have any custom DHCP domain name configuration on our cluster. I managed to make the nodes join the cluster by adding `--hostname-override=${HOSTNAME}.<region>.compute.internal` to the kubelet args. 
I'm currently trying to find way to make that solution permanent because we have a spot instance managed node group

**Comment by cartermckinnon** [comment]
It sounds like your OS is not using a fully-qualified domain name as the hostname, which will also cause this issue due to mismatch between the Node object name and EC2's `PrivateDnsName`. AL2 (like RHEL/CentOS) uses FQDNs by convention; and the official EKS AMI from Canonical uses FQDNs as well (despite the fact that Debian variants do not).

What AMI are you using, @pnpn?

**Comment by pnpn** [comment]
@cartermckinnon 
Thanks for replying :) We tried to use the `amazon-eks-node-1.26-v20230411` AMI ([ami-0b0000562f9e47337](https://eu-west-3.console.aws.amazon.com/ec2/home?region=eu-west-3#ImageDetails:imageId=ami-0b0000562f9e47337)),  we do not use any custom AMI for the cluster.

**Comment by pnpn** [comment]
Not that I know of, I will check but I think we have a setup that is quite classic.

**Comment by pnpn** [comment]
@cartermckinnon 
I looked and I didn't find anything that would override the hostname of the machines, I wanted to clarify that this is not a brand new cluster but one we upgraded everytime there was a new version from 1.21 and we only encountered this issue when we tried to upgrade fron 1.25 to 1.26. I'll try to do some tests on my own this week-end to see if I can find anything (or at least a satisfaying workaround) :)

**Comment by AustinRP-CapS** [comment]
@cartermckinnon 
We're also running into this issue similar to @pnpn. Using the same amazon-eks-node-1.26-v20230411 AMI, no custom domain names on the nodes, upgrade from 1.25 to 1.26

**Comment by mmerkes** [comment]
The `v20230501` release has started now, and it includes changes in #1264 that should fix this issue. New AMIs should be available in all regions late tonight (PDT).

**Comment by jitensingh12** [comment]
I'm facing same issue with EKS managed AMI : ami-0bc4534a93057f9fb... EKS: 1.27 (Latest) 
I've also disabled DNS hostname in VPC level and launched new EKS cluster (1.27) error is still same.
Relaunched the after enabling VPC DNS hostname and I'm using default DHCP set in AWS, no custom domain.

Error Logs: Aug 4 2023

Aug 04 18:56:15 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:15.163680 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:16 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:16.156733 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.177825 2998 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Unauthorized
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.266792 2998 kubelet_node_status.go:352] "Setting node annotation to enable volume controller attach/detach"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267838 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasSufficientMemory"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267880 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasNoDiskPressure"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267895 2998 kubelet_node_status.go:669] "Recording event message for node" node="ip-10-10-4-144.ec2.internal" event="NodeHasSufficientPID"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: I0804 18:56:17.267922 2998 kubelet_node_status.go:70] "Attempting to register node" node="ip-10-10-4-144.ec2.internal"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: E0804 18:56:17.343482 2998 controller.go:146] "Failed to ensure lease exists, will retry" err="Unauthorized" interval="7s"
Aug 04 18:56:17 ip-10-10-4-144.ec2.internal kubelet[2998]: E0804 18:56:17.343876 2998 kubelet_node_status.go:92] "Unable to register node with API server" err="Unauthorized" node="ip-10-10-4-144.ec2.internal"

@cartermckinnon
Contributor
Author
[cartermckinnon](https://github.com/cartermckinnon) commented [now](https://github.com/awslabs/amazon-eks-ami/pull/1264#issuecomment-1666046709)
@jitensingh12 Please open a new issue with the details of your environment and what error you're encountering.

**Comment by cartermckinnon** [comment]
This merged PR is not the right place to report a new issue. Please open a new issue.
