### ISSUE TITLE
SSM Agent Installation breaks Packer runs

### ISSUE THREAD

**Issue by thepoppingone** [awslabs/amazon-eks-ami#685]
**What happened**:
When custom AMI already has SSM agent the packer build fails

**What you expected to happen**:
skip the package gracefully

**How to reproduce it (as minimally and precisely as possible)**:
when packing another hardened AL2 AMI an error shows
amazon-ebs: Examining /var/tmp/yum-root-NaN4jm/amazon-ssm-agent.rpm: amazon-ssm-agent-3.0.1295.0-1.x86_64
amazon-ebs: /var/tmp/yum-root-NaN4jm/amazon-ssm-agent.rpm: does not update installed package.
amazon-ebs: Error: Nothing to do

25-Jun-2021 11:28:40 | ==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
-- | --
25-Jun-2021 11:28:40 | ==> amazon-ebs: Terminating the source AWS instance...
25-Jun-2021 11:30:10 | ==> amazon-ebs: Cleaning up any extra volumes...
25-Jun-2021 11:30:10 | ==> amazon-ebs: No volumes to clean up, skipping
25-Jun-2021 11:30:10 | ==> amazon-ebs: Deleting temporary security group...
25-Jun-2021 11:30:11 | ==> amazon-ebs: Deleting temporary keypair...
25-Jun-2021 11:30:11 | Build 'amazon-ebs' errored after 7 minutes 48 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
25-Jun-2021 11:30:11 |  
25-Jun-2021 11:30:11 | ==> Wait completed after 7 minutes 48 seconds
25-Jun-2021 11:30:11 |  
25-Jun-2021 11:30:11 | ==> Some builds didn't complete successfully and had errors:
25-Jun-2021 11:30:11 | --> amazon-ebs: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
25-Jun-2021 11:30:11 |  
25-Jun-2021 11:30:11 | ==> Builds finished but no artifacts were created.
25-Jun-2021 11:30:11 | make[1]: *** [Makefile:42: k8s] Error 1
25-Jun-2021 11:30:11 | make: *** [Makefile:61: 1.18] Error 2
25-Jun-2021 11:30:11 | cat: manifest.json: No such file or directory

**Anything else we need to know?**:
SSM agent exist previously so the packer step should skip this

**Environment**: Ubuntu running packer for AL2 custom ami
- AWS Region: ap-southeast-1
- Instance Type(s): t3.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 1.18
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.18
- AMI Version: using a AL2 ami
- Kernel (e.g. `uname -a`): NA
- Release information (run `cat /etc/eks/release` on a node): NA

```
```

**Comment by TrentPetersen04** [comment]
I just experienced this issue as well, would love to see a fix if SSM is already installed.

**Comment by fergus-orbach** [comment]
has anyone got a work around for this yet?

**Comment by fergus-orbach** [comment]
This has already been fixed with newest version of ssm-agent :)

**Comment by MyannaHarris** [comment]
Hi,

Can you please tell us what version of the AMI you are using or what release you are basing your custom AMI on?

@fergus-orbach Does the issue still exist in the EKS AMI? Is it only fixed in the latest ssm-agent version?

**Comment by TrentPetersen04** [comment]
@MyannaHarris 

Really sorry I missed your question before. Not sure if its still helpful in anyway, but our use case is that we build a hardened Amazon Linux 2 image for use within a Government setting. This base AMI includes SSM as well as some other AWS agents, and we submit that image for security and compliance review. Once that image has been approved we run this code to create hardened EKS compatible images.

This change broke our build process, when it would be expected that if SSM was present it would be detected and move on without failure. It appears this is now the case so it should be resolved. I will remove the "fix" we made and see if this is case.
